name: Metrics
on:
  schedule: [{cron: "0 18 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics-2026.svg
          base: ""
          plugin_isocalendar: yes
          # Mude para 90d (90 dias). Isso pega SÓ de Janeiro/2026 até agora!
          plugin_isocalendar_duration: 90d
